# Generated by Django 6.0.1 on 2026-06-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysisrecord_confidence_analysisrecord_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisrecord',
            old_name='confidence',
            new_name='accuracy_score',
        ),
    ]
