# Generated by Django 6.0.6 on 2026-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_confidence_analysisrecord_accuracy_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='original_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='processed_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
